### ISSUE TITLE
Can't start the extension?

### ISSUE THREAD

**Issue by Gruntfuggly** [Hirse/vscode-ungit#11]
After installation, if I try to start ungit, it get the error:

Error: command 'extension.ungit' not found

Vscode: 1.13.1 (Ubuntu)

**Comment by capaj** [comment]
me too. 
![image](https://user-images.githubusercontent.com/1305378/27624618-d2118bec-5be1-11e7-8a37-f42d134d5140.png)

which is weird because the command is there: https://github.com/Hirse/vscode-ungit/blob/master/package.json#L36

**Comment by Hirse** [comment]
The latest release might be broken, I'll look into it.

**Comment by RomanValihura** [comment]
Also have this problem

**Comment by Hirse** [comment]
Please try 1.0.3 and reopen if necessary.
