### ISSUE TITLE
every time I switch a tab ungit reinitializes again

### ISSUE THREAD

**Issue by capaj** [Hirse/vscode-ungit#2]
is there a way to prevent this? It can get quite slow if I have changed a lot of files because every time ungit has to build the change diff again.
Also my commit message gets lost.

**Comment by Hirse** [comment]
Unfortunately, there is nothing I can do about that as that behavior is intentional by VS Code: https://github.com/Microsoft/vscode/issues/15437
> When not visible (like changing tabs) we will dispose the state/document and recreate things on load. Also, when dragging tabs around we will rebuilt everything.

**Comment by capaj** [comment]
yes that is unfortunate. One would hope they would only dispose when the tab is closed but no. To rub the salt in the wound-the Atom ungit plugin works so well :pensive:
