### ISSUE TITLE
How do we get rid of the new-version banner?

### ISSUE THREAD

**Issue by whysorfrans** [Hirse/vscode-ungit#27]
This banner is too annoying (as is the help-improve banner), especially as it's repeated every time the window repaints

"A new version of ungit (1.2.2) is available! Run npm update -g ungit to install. See what's new in the changelog"

**Comment by Hirse** [comment]
For now I have updated the ungit version, so you shouldn't see the message with the next version. 
For the long term, I am checking the ungit config options to remove the version check.

The "help-improve" banner only showed up once for me.

**Comment by Hirse** [comment]
Change is live in [1.1.1](https://github.com/Hirse/vscode-ungit/releases/tag/v1.1.1).

**Comment by whysorfrans** [comment]
Thank you
