### ISSUE TITLE
Switching between editors and back to ungit causes to reload

### ISSUE THREAD

**Issue by bernardoadc** [Hirse/vscode-ungit#32]
Is this the intended behavior? When I switch to a file and then back to ungit, it reloads. This is different of when changing files on disk, when ungit rechecks the repository. When I say reload I mean load the entire repository, etc (tab is initially blank). This causes to be heavier without the need to.

![image](https://user-images.githubusercontent.com/9037461/33388251-9ac128f6-d516-11e7-8c52-f717b698ce90.png)

**Comment by Hirse** [comment]
It is definitely not intended by me, but it is indented behavior for the component being used and there doesn't seem to be a way to change it. 😞 
See https://github.com/Hirse/vscode-ungit/issues/2 and https://github.com/Microsoft/vscode/issues/15437.

**Comment by bernardoadc** [comment]
Unbelievable.. 🙄 
Perhaps add it to known issues?
(ps: sorry, should have looked in previous issues!)

**Comment by Hirse** [comment]
Good point. 
No worries, it is an annoying behavior. 😄
