### ISSUE TITLE
Feature : Is is possible to add a button to open start in the right top corner of VSCode ?

### ISSUE THREAD

**Issue by gigi206** [Hirse/vscode-ungit#54]
Hello,

Is is possible to add a button to start ungit in the right top corner of VSCode ? (with the possibility to hide or show this button in the configuration like "ungit.showButton": true).

Regards

**Comment by Hirse** [comment]
![2018-08-06_15-48-41](https://user-images.githubusercontent.com/2564094/43744712-367d18a2-9990-11e8-922a-3f8f7591ecfc.png)
Is this what you have in mind?

**Comment by gigi206** [comment]
Yes 👍

Thank you
