### ISSUE TITLE
don't split the view

### ISSUE THREAD

**Issue by zzzgit** [Hirse/vscode-ungit#59]
every time ungit is open, it will be displayed in a new view.

Is it possible to display it in the current view?

**Comment by Hirse** [comment]
The new version adds a setting to decide where to open it. Default is the current behavior, but you can set it to open in the current view:
https://github.com/Hirse/vscode-ungit/blob/b78d4728564cc9778a2001b877bbb710a45eaba7/package.json#L44-L49

Please try it out and let me know if that is what you had in mind.
