### ISSUE TITLE
Is it possible that ungit use the vscode git.path variable ?

### ISSUE THREAD

**Issue by gigi206** [Hirse/vscode-ungit#63]
There is a variable named **git.path** in vscode settings that allow to specify the path for the git binary.

For example GlitLens extension also used this variable for determine de git binary path.

Is it possible that ungit also used this variable for determine the git path ?

**Comment by Hirse** [comment]
This extension doesn't run `git` itself, but calls a locally installed `ungit` version.
I am not aware of a configuration option in ungit to do that, so I have opened an issue there.
If it is possible, I can pass the value of that setting along.

**Comment by gigi206** [comment]
Ok thank you :)

**Comment by gigi206** [comment]
It seems that a patch has already been released in version [1.4.36](https://github.com/FredrikNoren/ungit/commit/dbd54ad28400234aff35ff6b52c129b171888feb)

**Comment by Hirse** [comment]
Fixed in [v2.0.0](https://github.com/Hirse/vscode-ungit/releases/tag/v2.0.0).
