### ISSUE TITLE
Starting Ungit infinity

### ISSUE THREAD

**Issue by LeninZapata** [Hirse/vscode-ungit#68]
Hello, when I want to open the extension, it waits forever.
I do not know if I'm doing something wrong or something is happening.
Please tell me what may be happening.

Video ▶ http://recordit.co/xG48DhXnYS

**Comment by Hirse** [comment]
Thanks for the report.
I have seen very long times when debugging sometimes, but I never found a cause.
I have added a bit of error handling in [v2.0.0](https://github.com/Hirse/vscode-ungit/releases/tag/v2.0.0). I hope it helps.

**Comment by LeninZapata** [comment]
Install version 2.0.0 and it still does not work =/

**Comment by Hirse** [comment]
That's a shame. 
Can you please add some information about your environment (VSCode version, other extensions, type of project you are working on)?

**Comment by LeninZapata** [comment]
This is my list of plugins, I do not know if any of them would be causing a conflict but I would like you to review, because I want to use your extension.

ayu v0.18.0
  background-cover v1.5.1
  better-align v1.1.6
  better-comments v2.0.3
  Bookmarks v10.4.2
  bracket-pair-colorizer-2 v0.0.28
  branch-warnings v1.0.4
  city-lights-icon-vsc v1.1.3
  code-settings-sync v3.2.8
  color-highlight v2.3.0
  comment-anchors v1.6.1
  daily v6.0.3
  ftp-kr v1.3.16
  git-urgent v1.0.0
  gitlens v9.5.1
  html-css-class-completion v1.18.0
  html-preview-vscode v0.2.5
  html-snippets v0.2.1
  indent-rainbow v7.4.0
  jquerysnippets v0.0.1
  linesinfostatusbar v0.0.3
  minify v0.4.3
  notes v0.8.0
  one-monokai v0.3.7
  one-monokai-80s v1.3.16
  partial-diff v1.4.0
  php-debug v1.13.0
  php-intellisense v2.3.10
  project-manager v10.5.1
  snippets-project v0.0.2
  sqlformatter v0.0.7
  Theme-FlatlandMonokai v0.0.4
  theme-monokai-dark-soda v0.0.5
  theme-monokaisharp v1.0.0
  todotasks v0.5.0
  trailing-spaces v0.2.11
  ungit-tab v0.0.9
  unique-window-colors v1.0.23
  vscode-custom-css v3.0.3
  vscode-fix-checksums v1.1.0
  vscode-google-translate v1.1.5
  vscode-icontheme-nomo-dark v1.3.6
  vscode-insertdatestring v2.2.3
  vscode-intelephense-client v1.0.13
  vscode-language-pack-es v1.32.4
  vscode-mysql v0.4.0
  vscode-remind-me v0.1.0
  vscode-ungit v1.7.1
  vscode-wakatime v1.2.13
  wordpress-toolbox v1.3.3

My current project I choose in PHP, I make wordpress plugin
