### ISSUE TITLE
Deprecated command 'vscode.previewHtml'

### ISSUE THREAD

**Issue by bhgsbatista** [Hirse/vscode-ungit#72]
I got this warning today:

"Extension 'Hirse.vscode-ungit' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API."

VSCode version 1.32.1

**Comment by Hirse** [comment]
Thanks for the issue. 
I was aware of the new API, but didn't see the deprecation yet.

There will be an updated version soon.

**Comment by Hirse** [comment]
Fixed in [v2.0.0](https://github.com/Hirse/vscode-ungit/releases/tag/v2.0.0).
