### ISSUE TITLE
Impossible to write something in the title fill since VSCode 1.36

### ISSUE THREAD

**Issue by gigi206** [Hirse/vscode-ungit#79]
Since the upgrade to VSCode version 1.36, it seems there is an issue when I try to fill the title commit message. The cursor blink on the left panel and also on the ungit title field and when I try to write something, it writes only on the left panel. If I click on the ungit tab or if I close the left panel I don't see the cursor and I can't write.

Any idea ?

**Comment by gigi206** [comment]
I try to downgrade to version 1.35.1 and it works, and if I upgrade to version 1.36 it doesn't.

**Comment by Hirse** [comment]
Thanks for the report.
I just got an update to 1.36.1, but can still see the issue.

There seems to be some funky focus-capturing going on. VSCode keeps focus when you use the mouse to switch focus to the Ungit-tab, but when you use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> ungit gets focus and you can't change tabs with keyboard any more.

I will try to reproduce that with an easier Webview content, but it looks like it an issue with VSCode.

**Comment by gigi206** [comment]
Fixed since yesterday with version 1.40.2

Thank you for your help 👍
