### ISSUE TITLE
Fails to load when ungit server is already running

### ISSUE THREAD

**Issue by srfrnk** [Hirse/vscode-ungit#8]
When ungit command issued but ungit server has been started by another process the 'Loading...' screen stays on forever.
You need to manually kill ungit server for the plugin to resume correct operation.
It is not necessary that this happens as you can attach to the existing ungit server.

**Comment by LeninZapata** [comment]
I have the same problem, what can I do to solve it?
![image](https://user-images.githubusercontent.com/42600954/50407406-9194f480-07a4-11e9-8fd1-91a2acc5131d.png)
