### ISSUE TITLE
display too large view in splited view

### ISSUE THREAD

**Issue by cdll** [Hirse/vscode-ungit#90]
may it be optimized that Ungit graphs display too large in splited views as:
![image](https://user-images.githubusercontent.com/8576686/75431874-787b6b00-5988-11ea-97a2-f2abe11da2c9.png)

**Comment by Hirse** [comment]
Optimization for narrow viewports is something that would have to be done by [ungit ](https://github.com/FredrikNoren/ungit/) itself.

To mitigate the issue, you can configure vscode-ungit to not open in a split-view:
![image](https://user-images.githubusercontent.com/2564094/88240765-fa707700-cc3c-11ea-91c9-cfb4f765f745.png)
