### ISSUE TITLE
ungit plugin not working at all (@ VSCode) 

### ISSUE THREAD

**Issue by fwornle** [Hirse/vscode-ungit#95]
Hi,
I've trouble getting the VSCode plugin for ungit to work - seems that the plugin does not recognize any git repositories. Any idea why? For more information on the issue and the analysis thus far, please see the thread on the original ungit GitHub presence: https://github.com/FredrikNoren/ungit/issues/1402. Appears to be an issue with the plugin rather than ungit itself. Thanks.

**Comment by marie-bnl** [comment]
This seems to be the issue: https://github.com/yargs/yargs/issues/2287

ungit being forked from an electron process, it is being given its path as an argument, which he doesn't recognize so it just logs the usage and exits

**Comment by Hirse** [comment]
Should be fixed in #100 then. Please try the latest version.
