### ISSUE TITLE
extension won't start

### ISSUE THREAD

**Issue by vitalEol** [Hirse/vscode-ungit#96]
On the latest release of VScode (1.62.2) the current Ungit extension (v2.2.3) doesn't start - it stays at the loading prompt indefinitely
![image](https://user-images.githubusercontent.com/42639787/141986140-719653ca-c43a-481c-89d8-456d4859e2d1.png)

I'm not sure if there were changes to extensions in the latest release [](https://code.visualstudio.com/updates/v1_62) but this is still working on the previous release of VScode
![image](https://user-images.githubusercontent.com/42639787/141986869-bc8f1584-c4df-492d-bd19-4f94c530ea31.png)

**Comment by bartosz-m** [comment]
I've had same issue, installing globally latest ungit helped `npm i -g ungit@latest`
I'm not sure why that worked but maybe it will help in finding source of problem
