### ISSUE TITLE
I miss ungit

### ISSUE THREAD

**Issue by babyboomer53** [Hirse/vscode-ungit#97]
Ungit was my favorite git GUI. But now it's gone. :-( I suspect I first became acquainted with it while using Brackets. Eventually, I started using it with VS code. Regardless, it no longer seems to be working in either. This is what I get when I try launching it in VS code:

![ungit issues](https://user-images.githubusercontent.com/38309112/179298676-6fd174af-6ee8-47fd-9951-d3703300b1a9.png)

The window runs indefinitely. The behavior in Brackets is similar. Since I'm not getting any errors, I don't know how to proceed.

So, I decided to try running it from the commandline…

![ungit error](https://user-images.githubusercontent.com/38309112/181844034-4008903c-0737-4528-b4e6-96af5eab0a32.png)

Perhaps I need to include a command-line option to use it this way.

**Comment by babyboomer53** [comment]
I will conduct more research and repost if required.

**Comment by Hirse** [comment]
I published a new version yesterday. Please try updating the extension and let me know if you still have any issues. 😄
