### ISSUE TITLE
Open the view in a tab, not in a split view

### ISSUE THREAD

**Issue by Deltavion** [Hirse/vscode-ungit#99]
I just want to know if it is possible to prevent the ungit view from opening in split view.
Thanks

**Comment by Hirse** [comment]
See my reply in #90:
> You can configure vscode-ungit to not open in a split-view: ![image](https://user-images.githubusercontent.com/2564094/88240765-fa707700-cc3c-11ea-91c9-cfb4f765f745.png)

**Comment by Deltavion** [comment]
Thanks !
